### ISSUE TITLE
Implement new SDEC mitigators

### ISSUE THREAD

**Issue by matt-dray** [The-Strategy-Unit/nhp_inputs#450]
Generate a module for the SDEC mitigators, rather than AEC (i.e. replace [the module generation in `app_server.R`](https://github.com/The-Strategy-Unit/nhp_inputs/blob/47a14e5ef2fa8041294ab0f0761d8aab3e32c6ab/R/app_server.R#L123)). Also need to update associated files and references to these mitigators where needed, e.g. `golem-config.yml`, `mitigators.Rds`. May need to adjust the associated Markdowns in `strategy_text/`.

**Comment by matt-dray** [comment]
Presumably config will be like:
```
    mitigators_sdec_los_reduction:  # was 'aec'
      activity_type: aae  # ip to aae
      mitigators_type: efficiencies
      y_axis_title: "% admissions with a greater than 0-day length of stay"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Number of Admissions"
      slider_scale: 100
      slider_step: 0.1
      strategy_subset:  # was 'ambulatory'/'Ambulatory'
        same_day_emergency_care_low: "Same Day Emergency Care (Low Potential)"
        same_day_emergency_care_moderate: "Same Day Emergency Care (Moderate Potential)"
        same_day_emergency_care_high: "Same Day Emergency Care (High Potential)"
        same_day_emergency_care_very_high: "Same Day Emergency Care (Very High Potential)"
      params_items:
        type: "sdec"  # was 'aec'
```

**Comment by tomjemmett** [comment]
```
    mitigators_sdec_conversion:
      activity_type: ip
      mitigators_type: efficiencies
      y_axis_title: "Admissions per 1,000 population"
      x_axis_title: "Financial Year"
      number_type: !expr scales::percent_format()
      funnel_x_title: "Catchment Population of Trust"
      funnel_number_type: !expr scales::comma_format()
      slider_scale: 100
      slider_step: 0.1
```

I think its going to look something like this, but would need to check. changed the name to sdec_conversion, used most of the same values as activity avoidance (the values are done in the same way as the avoidance ones now).
